kind = "web"
previewPath = "/"
title = "B.B. Airconditions"
version = "1.0.0"
id = "artifacts/bb-airconditions"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25375

[services.development]
run = "pnpm --filter @workspace/bb-airconditions run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bb-airconditions", "run", "build" ]
publicDir = "artifacts/bb-airconditions/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25375"
BASE_PATH = "/"
